services:
  api:
    image: simplify:1.0
    depends_on:
      - mysql
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - simplify-net

  mysql:
    container_name: mysql-server
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - simplify-net

networks:
  simplify-net:
    driver: bridge