spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/todos?createDatabaseIfNotExist=true
    username: root
    password: 12345

  jpa:
    hibernate:
      ddlAuto: update
      showSql: true
